INFERENCE_VALUE_RESPONSE_KEY = 'inference-value'
INFERENCE_LANGUAGE_RESPONSE_KEY = 'inference-language'
CURRENT_FILE_TEXT_PARAM_NAME = 'current-file-text'
OPENAI_KEY_PARAM_NAME = 'openai-key'
OPENAI_ORGANIZATION_ID_PARAM_NAME = 'openai-organization-id'
GOOGLE_OAUTH_KEY = 'google-oauth'
